with open('CDVERSION.tmp', 'r') as cdfile :
  cdfiledata = cdfile.read()
commastring = cdfiledata.replace('.', ', ')

f = open("file_version_info.txt", "a")
f.write("# UTF-8")
f.write("#")
f.write("# For more details about fixed file info 'ffi' see:")
f.write("# http://msdn.microsoft.com/en-us/library/ms646997.aspx")
f.write("VSVersionInfo(")
f.write("  ffi=FixedFileInfo(")
f.write("    # filevers and prodvers should be always a tuple with four items: (1, 2, 3, 4)")
f.write("    # Set not needed items to zero 0.")
f.write("    filevers=(" + commastring + ", 0),")
f.write("    prodvers=(" + commastring + ", 0),")
f.write("    # Contains a bitmask that specifies the valid bits 'flags'r")
f.write("    mask=0x0,")
f.write("    # Contains a bitmask that specifies the Boolean attributes of the file.")
f.write("    flags=0x0,")
f.write("    # The operating system for which this file was designed.")
f.write("    # 0x4 - NT and there is no need to change it.")
f.write("    OS=0x4,")
f.write("    # The general type of file.")
f.write("    # 0x1 - the file is an application.")
f.write("    fileType=0x1,")
f.write("    # The function of the file.")
f.write("    # 0x0 - the function is not defined for this fileType")
f.write("    subtype=0x0,")
f.write("    # Creation date and time stamp.")
f.write("    date=(0, 0)")
f.write("    ),")
f.write("  kids=[")
f.write("    StringFileInfo(")
f.write("      [")
f.write("      StringTable(")
f.write("        '040904E4',")
f.write("        [StringStruct('CompanyName', 'Do Team'),")
f.write("        StringStruct('ProductName', 'DoElvUIClient'),")
f.write("        StringStruct('ProductVersion', '" + commastring + ",0'),")
f.write("        StringStruct('InternalName', 'DoElvUIClient'),")
f.write("        StringStruct('OriginalFilename', ''),")
f.write("        StringStruct('FileVersion', '" + cdfiledata + "'),")
f.write("        StringStruct('FileDescription', 'DoElvUIClient'),")
f.write("        StringStruct('LegalCopyright', ''),")
f.write("        StringStruct('LegalTrademarks', '')])")
f.write("      ]),")
f.write("    VarFileInfo([VarStruct('Translation', [1033, 1252])])")
f.write("  ]")
f.write(")")
f.close()