with open('CDVERSION.tmp', 'r') as cdfile :
  cdfiledata = cdfile.read()
cdfiledataparsed = cdfiledata.replace('v', '')
commastring = cdfiledataparsed.replace('.', ',')

f = open("file_version_info.txt", "a")
f.write("# UTF-8\n")
f.write("#\n")
f.write("# For more details about fixed file info 'ffi' see:\n")
f.write("# http://msdn.microsoft.com/en-us/library/ms646997.aspx\n")
f.write("VSVersionInfo(\n")
f.write("  ffi=FixedFileInfo(\n")
f.write("    # filevers and prodvers should be always a tuple with four items: (1, 2, 3, 4)\n")
f.write("    # Set not needed items to zero 0.\n")
f.write("    filevers=(" + commastring + ",0),\n")
f.write("    prodvers=(" + commastring + ",0),\n")
f.write("    # Contains a bitmask that specifies the valid bits 'flags'r\n")
f.write("    mask=0x0,\n")
f.write("    # Contains a bitmask that specifies the Boolean attributes of the file.\n")
f.write("    flags=0x0,\n")
f.write("    # The operating system for which this file was designed.\n")
f.write("    # 0x4 - NT and there is no need to change it.\n")
f.write("    OS=0x4,\n")
f.write("    # The general type of file.\n")
f.write("    # 0x1 - the file is an application.\n")
f.write("    fileType=0x1,\n")
f.write("    # The function of the file.\n")
f.write("    # 0x0 - the function is not defined for this fileType\n")
f.write("    subtype=0x0,\n")
f.write("    # Creation date and time stamp.\n")
f.write("    date=(0, 0)\n")
f.write("    ),\n")
f.write("  kids=[\n")
f.write("    StringFileInfo(\n")
f.write("      [\n")
f.write("      StringTable(\n")
f.write("        '040904E4',\n")
f.write("        [StringStruct('CompanyName', 'Do Team'),\n")
f.write("        StringStruct('ProductName', 'DoElvUIClient'),\n")
f.write("        StringStruct('ProductVersion', '" + commastring + ",0'),\n")
f.write("        StringStruct('InternalName', 'DoElvUIClient'),\n")
f.write("        StringStruct('OriginalFilename', ''),\n")
f.write("        StringStruct('FileVersion', '" + cdfiledataparsed + "'),\n")
f.write("        StringStruct('FileDescription', 'DoElvUIClient'),\n")
f.write("        StringStruct('LegalCopyright', ''),\n")
f.write("        StringStruct('LegalTrademarks', '')])\n")
f.write("      ]),\n")
f.write("    VarFileInfo([VarStruct('Translation', [1033, 1252])])\n")
f.write("  ]\n")
f.write(")\n")
f.close()